services:
  # PostgreSQL Database
  - type: pserv
    name: therapy-companion-db
    env: postgres
    plan: free
    databaseName: therapy_companion
    user: therapy_user

  # Web Service
  - type: web
    name: therapy-companion
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./startup.sh"
    envVars:
      - key: PRODUCTION
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: therapy-companion-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: new_backendstep3.py
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
      - key: SYSTEM_EMAIL
        sync: false
      - key: SYSTEM_EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
